### ISSUE TITLE
Client IP is not your visitor's IP!

### ISSUE THREAD

**Issue by Firsh** [mraichelson/netlify-ip-function#1]
Dump `event.headers` and you'll [see](https://examples.netlify.horse/withexpress). Look at these instead:

- `forwarded`
- `x-bb-ip`
- `x-forwarded-for`
- `x-nf-client-connection-ip`

The last one is [probably best](https://answers.netlify.com/t/is-the-client-ip-header-going-to-be-supported-long-term/11203). I see my IP only in these.

**Comment by mraichelson** [comment]
Yeah, I need to come back to this. Different options are returned in local `netlify dev` environments and when things are deployed to actual netlify servers as well.

**Comment by Firsh** [comment]
BTW your script inspired me to put GA tracking in the Netlify function (proxy) so only the data I control arrives there and eventually uses Measurement Protocol. The visitor doesn't see anything related to Google Analytics. Nor can they fingerprint my users.

**Comment by mraichelson** [comment]
Nice!

I know there's an example of doing that over here but I've never really tried to dissect it and try it for myself.  https://github.com/google/eleventy-high-performance-blog/blob/main/functions/ga.js

(My day job leans pretty heavily on GTM for managing analytics and I've been using [Plausible](https://plausible.io/) for personal stuff.)

**Comment by mraichelson** [comment]
As noted back in the day `x-nf-client-connection-ip` is the actual header that this should have been looking at.

Finally got up and actually adjusted the code.

Thanks again @Firsh.
